//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiteHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hebergement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hebergement()
        {
            this.Conversations = new HashSet<Conversation>();
            this.Messageries = new HashSet<Messagerie>();
            this.Photos = new HashSet<Photo>();
            this.Reservations = new HashSet<Reservation>();
            this.Tarifications = new HashSet<Tarification>();
            this.Avis = new HashSet<Avi>();
            this.Equipements = new HashSet<Equipement>();
            this.Fournitures = new HashSet<Fourniture>();
            this.Clients = new HashSet<Client>();
            this.MoyenPaiements = new HashSet<MoyenPaiement>();
            this.Themes = new HashSet<Theme>();
        }
    
        public int IdHebergement { get; set; }
        public int IdTypeHebergement { get; set; }
        public int IdDestination { get; set; }
        public int IdProprietaire { get; set; }
        public Nullable<int> IdLabel { get; set; }
        public int IdAdresse { get; set; }
        public Nullable<int> Ordre { get; set; }
        public string Nom { get; set; }
        public string DescriptionCourte { get; set; }
        public string DescriptionLongue { get; set; }
        public Nullable<int> Surface { get; set; }
        public Nullable<int> NombrePiece { get; set; }
        public Nullable<int> NombreChambre { get; set; }
        public Nullable<bool> Animaux { get; set; }
        public string CouleurReservation { get; set; }
        public Nullable<decimal> PrixBase { get; set; }
        public Nullable<bool> Statut { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Label Label { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
        public virtual TypeHebergement TypeHebergement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messagerie> Messageries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarification> Tarifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avi> Avis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipement> Equipements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fourniture> Fournitures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoyenPaiement> MoyenPaiements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Theme> Themes { get; set; }
    }
}
