//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiteHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messagerie
    {
        public int IdMessagerie { get; set; }
        public int IdUtilisateur { get; set; }
        public int IdHebergement { get; set; }
        public string Email { get; set; }
        public string Titre { get; set; }
        public string Texte { get; set; }
    
        public virtual Hebergement Hebergement { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
