//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiteHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarification
    {
        public int IdTarification { get; set; }
        public int IdHebergement { get; set; }
        public int IdSaison { get; set; }
        public decimal PrixNuit { get; set; }
    
        public virtual Hebergement Hebergement { get; set; }
        public virtual Saison Saison { get; set; }
    }
}
